include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude: [build/**, lib/*.g.dart, lib/*.g.dart]

linter:
  rules:

    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    # prefer_double_quotes: true

    # Good packages document everything
    # public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    # lines_longer_than_80_chars: true