# When the iop_sdk is available on pub dev, enable pipeline on Gitlab
image: cirrusci/flutter:stable

stages:
  - analyze
  - test

analyze:
  stage: analyze
  before_script:
    - flutter pub get
  script:
    - flutter analyze

flutter_test:
  stage: test
  script:
    - flutter test
