include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_specify_types: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: true
